### ISSUE TITLE
Error when pulling image

### ISSUE THREAD

**Issue by cjellick** [rancherio/python-agent#91]
While attempting to run a validation test against my gce cluster, I ran into the following error while creating a new container. I'm on master of cattle and python-agent.

Here's the container request that causes it:
```
curl -u "<username:password>" -X POST -H 'Accept: application/json' \
-H 'Content-Type: application/json' -d \
'{"imageUuid":"docker:cattle/test-agent:v7", "networkIds":["1n2"], "ports":[], "startOnCreate":true, "command":"echo \"hello\"", "commandArgs":[], "publishAllPorts":false, "privileged":false, "capAdd":[], "capDrop":[], "dns":[], "dnsSearch":[], "stdinOpen":false, "tty":false, "entryPoint":[], "restartPolicy":null, "devices":[], "dataVolumes":[], "dataVolumesFrom":[]}' 'http://localhost:8080/v1/containers'
```

Here's the stack trace:
```
2015-03-13 14:53:28,114 ERROR agent [140462718918000] [event.py:108] 3c711f4c-54a1-4162-883e-1d3748dcd891 : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 33, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 23, in image_activate
    action=lambda: self._do_image_activate(image, storage_pool,
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 71, in _do
    action()
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 24, in <lambda>
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 80, in _do_image_activate
    auth_config=auth_config,
UnboundLocalError: local variable 'auth_config' referenced before assignment
```
And here's the event that was sent to python-agent that caused the error:
```
2015-03-13 14:53:27,934 INFO agent [140462718918000] [utils.py:408] Request: {
    "context": {
        "logicName": "ImageStoragePoolMapActivate",
        "logicPath": "instance.start->(InstanceStart)->volume.activate->(VolumeActivate)->imagestoragepoolmap.activate->(ImageStoragePoolMapActivate)",
        "prettyProcess": "instance.start->imagestoragepoolmap.activate",
        "prettyResource": "instance:65->imageStoragePoolMap:66",
        "processId": "323",
        "processName": "imagestoragepoolmap.activate",
        "processUuid": "a723e3b7-fc61-49b8-bac4-e5d499188543",
        "resouceId": "66",
        "resouceType": "imageStoragePoolMap",
        "topProcessName": "instance.start",
        "topResourceId": "65",
        "topResourceType": "instance"
    },
    "data": {
        "imageStoragePoolMap": {
            "created": 1426258407024,
            "data": {
                "fields": {}
            },
            "description": null,
            "id": 66,
            "image": {
                "accountId": 1,
                "checksum": null,
                "created": 1426258398986,
                "data": {
                    "dockerImage": {
                        "fullName": "cattle/test-agent:v7",
                        "id": null,
                        "lookUpName": "cattle/test-agent",
                        "namespace": "cattle",
                        "qualifiedName": "cattle/test-agent",
                        "repository": "test-agent",
                        "server": "index.docker.io",
                        "tag": "v7"
                    },
                    "fields": {}
                },
                "description": null,
                "format": "docker",
                "id": 65,
                "instanceKind": "container",
                "isPublic": false,
                "kind": "image",
                "name": "cattle/test-agent:v7",
                "physicalSizeMb": null,
                "registryCredential": null,
                "registryCredentialId": null,
                "removeTime": null,
                "removed": null,
                "state": "active",
                "type": "image",
                "url": null,
                "uuid": "d3b46de8-aec8-4aa6-8869-52c8565a640b",
                "virtualSizeMb": null
            },
            "imageId": 65,
            "kind": "imageStoragePoolMap",
            "name": null,
            "removeTime": null,
            "removed": null,
            "state": "activating",
            "storagePool": {
                "accountId": 1,
                "agentId": 4,
                "created": 1426199194758,
                "data": {
                    "fields": {
                        "hostUuid": "31c832d6-dd99-49c6-be80-286793631efa",
                        "reportedUuid": "31c832d6-dd99-49c6-be80-286793631efa-pool",
                        "type": "storagePool"
                    }
                },
                "description": null,
                "external": false,
                "id": 6,
                "kind": "docker",
                "name": "craig-10acre-2 Storage Pool",
                "physicalTotalSizeMb": null,
                "removeTime": null,
                "removed": null,
                "state": "active",
                "type": "storagePool",
                "uuid": "1798065e-c0e5-4bda-a30a-435dc273ce7b",
                "virtualTotalSizeMb": null,
                "zoneId": 1
            },
            "storagePoolId": 6,
            "type": "imageStoragePoolMap",
            "uuid": "3f3562f1-1568-4dec-a7a9-6582c77027bf"
        }
    },
    "id": "0ed47b4d-4109-41e2-b900-90ed6a89ce28",
    "name": "storage.image.activate",
    "previousIds": null,
    "previousNames": null,
    "publisher": null,
    "replyTo": "reply.949036583587006804",
    "resourceId": "66",
    "resourceType": "imageStoragePoolMap",
    "time": 1426258407905,
    "timeoutMillis": 15000,
    "transitioning": null,
    "transitioningInternalMessage": null,
    "transitioningMessage": null,
    "transitioningProgress": null
}
```

**Comment by hibooboo2** [comment]
See PR #92
